### PR TITLE
add min and max partition keys to tablet report output

### PR DESCRIPTION
**Pull request by kerneljake**
This change provides clarity to the user plus it ensures a fixed number of columns which makes writing perl script parsers easier.

Test procedure:
$ sqlite3 -header -column before.db
sqlite> select * from tablet;
$ yugatool --master-addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 cluster_info --tablet-report  | perl ./tablet-report-parser.pl | sqlite3 after.db
$ sqlite3 -header -column after.db 
sqlite> select * from tablet;

### CODE REVIEW

**Comment by tvesely** [comment]
Yeah, I agree that it's sub-optimal that the keys are blank when it the tablet is set to `partitionKeyStart` or `partitionKeyEnd`, but this function is generic for changing base64 to hex.

Perhaps it would be better if we added a new function that is specifically to decode the partition key that shares code with `base64_to_hex`?

**Comment by kerneljake** [comment]
@tvesely If I changed the name of the function to be `partition_key_to_hex`, would that work?  The present function is called in only one place -- for that sole purpose.

**Comment by tvesely** [comment]
Works for me- if I need a generic `base64_to_hex` function again in the future I can refactor.

**Comment by tvesely** [comment]
LGTM

**Pull request merged**
